version: '2'
services:
    proxy:
        image: nginx:1.13
        ports:
            - "8000:80"
        depends_on:
            - php
        volumes:
            - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
          - php

    php:
        build:
          dockerfile: ops/php/Dockerfile
          context: .
          args:
            - user=${UID}
        volumes:
          - ./sendy:/usr/share/nginx/html
        user: ${UID}:${UID}
    
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=pass
          - MYSQL_DATABASE=db

          



